// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: spot_instrument_service.proto

package spot_instrument

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_ADMIN  UserRole = 0
	UserRole_BROKER UserRole = 1
	UserRole_USER   UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "ADMIN",
		1: "BROKER",
		2: "USER",
	}
	UserRole_value = map[string]int32{
		"ADMIN":  0,
		"BROKER": 1,
		"USER":   2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_spot_instrument_service_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_spot_instrument_service_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_spot_instrument_service_proto_rawDescGZIP(), []int{0}
}

type ViewMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRoles     UserRole               `protobuf:"varint,1,opt,name=user_roles,json=userRoles,proto3,enum=proto.spot_instrument.UserRole" json:"user_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsRequest) Reset() {
	*x = ViewMarketsRequest{}
	mi := &file_spot_instrument_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsRequest) ProtoMessage() {}

func (x *ViewMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsRequest) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_proto_rawDescGZIP(), []int{0}
}

func (x *ViewMarketsRequest) GetUserRoles() UserRole {
	if x != nil {
		return x.UserRoles
	}
	return UserRole_ADMIN
}

type ViewMarketsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Markets       []*ViewMarketsResponse_Market `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse) Reset() {
	*x = ViewMarketsResponse{}
	mi := &file_spot_instrument_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse) ProtoMessage() {}

func (x *ViewMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketsResponse) GetMarkets() []*ViewMarketsResponse_Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

type ViewMarketsResponse_Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketUuid    []byte                 `protobuf:"bytes,1,opt,name=market_uuid,json=marketUuid,proto3" json:"market_uuid,omitempty"`
	MarketName    string                 `protobuf:"bytes,2,opt,name=market_name,json=marketName,proto3" json:"market_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse_Market) Reset() {
	*x = ViewMarketsResponse_Market{}
	mi := &file_spot_instrument_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse_Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse_Market) ProtoMessage() {}

func (x *ViewMarketsResponse_Market) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse_Market.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse_Market) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ViewMarketsResponse_Market) GetMarketUuid() []byte {
	if x != nil {
		return x.MarketUuid
	}
	return nil
}

func (x *ViewMarketsResponse_Market) GetMarketName() string {
	if x != nil {
		return x.MarketName
	}
	return ""
}

var File_spot_instrument_service_proto protoreflect.FileDescriptor

const file_spot_instrument_service_proto_rawDesc = "" +
	"\n" +
	"\x1dspot_instrument_service.proto\x12\x15proto.spot_instrument\"T\n" +
	"\x12ViewMarketsRequest\x12>\n" +
	"\n" +
	"user_roles\x18\x01 \x01(\x0e2\x1f.proto.spot_instrument.UserRoleR\tuserRoles\"\xae\x01\n" +
	"\x13ViewMarketsResponse\x12K\n" +
	"\amarkets\x18\x01 \x03(\v21.proto.spot_instrument.ViewMarketsResponse.MarketR\amarkets\x1aJ\n" +
	"\x06Market\x12\x1f\n" +
	"\vmarket_uuid\x18\x01 \x01(\fR\n" +
	"marketUuid\x12\x1f\n" +
	"\vmarket_name\x18\x02 \x01(\tR\n" +
	"marketName*+\n" +
	"\bUserRole\x12\t\n" +
	"\x05ADMIN\x10\x00\x12\n" +
	"\n" +
	"\x06BROKER\x10\x01\x12\b\n" +
	"\x04USER\x10\x022}\n" +
	"\x15SpotInstrumentService\x12d\n" +
	"\vViewMarkets\x12).proto.spot_instrument.ViewMarketsRequest\x1a*.proto.spot_instrument.ViewMarketsResponseB\x17Z\x15proto/spot_instrumentb\x06proto3"

var (
	file_spot_instrument_service_proto_rawDescOnce sync.Once
	file_spot_instrument_service_proto_rawDescData []byte
)

func file_spot_instrument_service_proto_rawDescGZIP() []byte {
	file_spot_instrument_service_proto_rawDescOnce.Do(func() {
		file_spot_instrument_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spot_instrument_service_proto_rawDesc), len(file_spot_instrument_service_proto_rawDesc)))
	})
	return file_spot_instrument_service_proto_rawDescData
}

var file_spot_instrument_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spot_instrument_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spot_instrument_service_proto_goTypes = []any{
	(UserRole)(0),                      // 0: proto.spot_instrument.UserRole
	(*ViewMarketsRequest)(nil),         // 1: proto.spot_instrument.ViewMarketsRequest
	(*ViewMarketsResponse)(nil),        // 2: proto.spot_instrument.ViewMarketsResponse
	(*ViewMarketsResponse_Market)(nil), // 3: proto.spot_instrument.ViewMarketsResponse.Market
}
var file_spot_instrument_service_proto_depIdxs = []int32{
	0, // 0: proto.spot_instrument.ViewMarketsRequest.user_roles:type_name -> proto.spot_instrument.UserRole
	3, // 1: proto.spot_instrument.ViewMarketsResponse.markets:type_name -> proto.spot_instrument.ViewMarketsResponse.Market
	1, // 2: proto.spot_instrument.SpotInstrumentService.ViewMarkets:input_type -> proto.spot_instrument.ViewMarketsRequest
	2, // 3: proto.spot_instrument.SpotInstrumentService.ViewMarkets:output_type -> proto.spot_instrument.ViewMarketsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spot_instrument_service_proto_init() }
func file_spot_instrument_service_proto_init() {
	if File_spot_instrument_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spot_instrument_service_proto_rawDesc), len(file_spot_instrument_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spot_instrument_service_proto_goTypes,
		DependencyIndexes: file_spot_instrument_service_proto_depIdxs,
		EnumInfos:         file_spot_instrument_service_proto_enumTypes,
		MessageInfos:      file_spot_instrument_service_proto_msgTypes,
	}.Build()
	File_spot_instrument_service_proto = out.File
	file_spot_instrument_service_proto_goTypes = nil
	file_spot_instrument_service_proto_depIdxs = nil
}
