// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: spot_instrument_service.proto

package spot_instrument

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	user_service "proto/user_service"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRole      user_service.UserRole  `protobuf:"varint,1,opt,name=user_role,json=userRole,proto3,enum=proto.user_service.UserRole" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsRequest) Reset() {
	*x = ViewMarketsRequest{}
	mi := &file_spot_instrument_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsRequest) ProtoMessage() {}

func (x *ViewMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsRequest) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_proto_rawDescGZIP(), []int{0}
}

func (x *ViewMarketsRequest) GetUserRole() user_service.UserRole {
	if x != nil {
		return x.UserRole
	}
	return user_service.UserRole(0)
}

type ViewMarketsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Markets       []*ViewMarketsResponse_Market `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse) Reset() {
	*x = ViewMarketsResponse{}
	mi := &file_spot_instrument_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse) ProtoMessage() {}

func (x *ViewMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketsResponse) GetMarkets() []*ViewMarketsResponse_Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

type ViewMarketsResponse_Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketUuid    []byte                 `protobuf:"bytes,1,opt,name=market_uuid,json=marketUuid,proto3" json:"market_uuid,omitempty"`
	MarketName    string                 `protobuf:"bytes,2,opt,name=market_name,json=marketName,proto3" json:"market_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse_Market) Reset() {
	*x = ViewMarketsResponse_Market{}
	mi := &file_spot_instrument_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse_Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse_Market) ProtoMessage() {}

func (x *ViewMarketsResponse_Market) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse_Market.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse_Market) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ViewMarketsResponse_Market) GetMarketUuid() []byte {
	if x != nil {
		return x.MarketUuid
	}
	return nil
}

func (x *ViewMarketsResponse_Market) GetMarketName() string {
	if x != nil {
		return x.MarketName
	}
	return ""
}

var File_spot_instrument_service_proto protoreflect.FileDescriptor

const file_spot_instrument_service_proto_rawDesc = "" +
	"\n" +
	"\x1dspot_instrument_service.proto\x12\x15proto.spot_instrument\x1a\x12user_service.proto\"O\n" +
	"\x12ViewMarketsRequest\x129\n" +
	"\tuser_role\x18\x01 \x01(\x0e2\x1c.proto.user_service.UserRoleR\buserRole\"\xae\x01\n" +
	"\x13ViewMarketsResponse\x12K\n" +
	"\amarkets\x18\x01 \x03(\v21.proto.spot_instrument.ViewMarketsResponse.MarketR\amarkets\x1aJ\n" +
	"\x06Market\x12\x1f\n" +
	"\vmarket_uuid\x18\x01 \x01(\fR\n" +
	"marketUuid\x12\x1f\n" +
	"\vmarket_name\x18\x02 \x01(\tR\n" +
	"marketName2}\n" +
	"\x15SpotInstrumentService\x12d\n" +
	"\vViewMarkets\x12).proto.spot_instrument.ViewMarketsRequest\x1a*.proto.spot_instrument.ViewMarketsResponseB\x17Z\x15proto/spot_instrumentb\x06proto3"

var (
	file_spot_instrument_service_proto_rawDescOnce sync.Once
	file_spot_instrument_service_proto_rawDescData []byte
)

func file_spot_instrument_service_proto_rawDescGZIP() []byte {
	file_spot_instrument_service_proto_rawDescOnce.Do(func() {
		file_spot_instrument_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spot_instrument_service_proto_rawDesc), len(file_spot_instrument_service_proto_rawDesc)))
	})
	return file_spot_instrument_service_proto_rawDescData
}

var file_spot_instrument_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spot_instrument_service_proto_goTypes = []any{
	(*ViewMarketsRequest)(nil),         // 0: proto.spot_instrument.ViewMarketsRequest
	(*ViewMarketsResponse)(nil),        // 1: proto.spot_instrument.ViewMarketsResponse
	(*ViewMarketsResponse_Market)(nil), // 2: proto.spot_instrument.ViewMarketsResponse.Market
	(user_service.UserRole)(0),         // 3: proto.user_service.UserRole
}
var file_spot_instrument_service_proto_depIdxs = []int32{
	3, // 0: proto.spot_instrument.ViewMarketsRequest.user_role:type_name -> proto.user_service.UserRole
	2, // 1: proto.spot_instrument.ViewMarketsResponse.markets:type_name -> proto.spot_instrument.ViewMarketsResponse.Market
	0, // 2: proto.spot_instrument.SpotInstrumentService.ViewMarkets:input_type -> proto.spot_instrument.ViewMarketsRequest
	1, // 3: proto.spot_instrument.SpotInstrumentService.ViewMarkets:output_type -> proto.spot_instrument.ViewMarketsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spot_instrument_service_proto_init() }
func file_spot_instrument_service_proto_init() {
	if File_spot_instrument_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spot_instrument_service_proto_rawDesc), len(file_spot_instrument_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spot_instrument_service_proto_goTypes,
		DependencyIndexes: file_spot_instrument_service_proto_depIdxs,
		MessageInfos:      file_spot_instrument_service_proto_msgTypes,
	}.Build()
	File_spot_instrument_service_proto = out.File
	file_spot_instrument_service_proto_goTypes = nil
	file_spot_instrument_service_proto_depIdxs = nil
}
