services:
  prometheus:
    image: prom/prometheus:latest
    ports: 
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    